import json
import os
import re
import secrets
import shutil
import subprocess
from datetime import datetime
from pathlib import Path

# Load .env file if present (secrets generated by install.sh)
_env_file = Path(__file__).parent / ".env"
if _env_file.exists():
    for line in _env_file.read_text().splitlines():
        if "=" in line and not line.startswith("#"):
            k, v = line.split("=", 1)
            os.environ.setdefault(k.strip(), v.strip())

import feedparser
import requests
from flask import (
    Flask,
    Response,
    jsonify,
    redirect,
    render_template,
    render_template_string,
    request,
    send_from_directory,
    session,
    flash,
)
from werkzeug.utils import secure_filename

import cache
import config
import models
from scheduler import (
    acknowledge_reminder,
    get_active_reminders,
    get_next_pill_info,
    reminder_queue,
    start_scheduler,
    stop_scheduler,
)

app = Flask(__name__)
app_start_time = datetime.now()

# Content exclusions — anime, foreign language films not suitable for Don & Colleen
_excluded_ids = set()
_exclusions_path = os.path.join(config.BASE_DIR, "content_exclusions.json")
if os.path.exists(_exclusions_path):
    with open(_exclusions_path) as _f:
        _excluded_ids = set(json.load(_f).get("excluded_ids", []))
app.config["SECRET_KEY"] = config.SECRET_KEY
app.config["MAX_CONTENT_LENGTH"] = config.MAX_UPLOAD_SIZE
app.config["SESSION_COOKIE_HTTPONLY"] = True
app.config["SESSION_COOKIE_SAMESITE"] = "Lax"


@app.template_filter("timeago")
def timeago_filter(timestamp_str):
    """Convert timestamp to '5m ago' style string."""
    try:
        dt = datetime.strptime(str(timestamp_str)[:19], "%Y-%m-%d %H:%M:%S")
        mins = int((datetime.now() - dt).total_seconds() / 60)
        if mins < 1:
            return "Just now"
        if mins < 60:
            return f"{mins}m ago"
        if mins < 1440:
            return f"{mins // 60}h ago"
        return f"{mins // 1440}d ago"
    except Exception:
        return ""


def _safe_int(value, default=0):
    """Convert to int, returning default if value is None or non-numeric."""
    try:
        return int(value)
    except (TypeError, ValueError):
        return default


def _is_local_request():
    """Check if request is from LAN (no auth needed) vs remote (needs auth)."""
    # If CF-Connecting-IP header exists, request came through Cloudflare tunnel = REMOTE
    if request.headers.get("CF-Connecting-IP"):
        return False
    # No CF header = direct access. Check if it's from LAN.
    ip = request.remote_addr or ""
    if ip.startswith("192.168.") or ip.startswith("10.") or ip.startswith("172.") or ip == "127.0.0.1":
        return True
    return False


@app.before_request
def check_remote_auth():
    """Require password for ALL remote (Cloudflare tunnel) access."""
    if _is_local_request():
        return  # LAN users skip auth entirely — Don & Colleen never see login
    # Allow login page, static assets, and API endpoints without auth
    # APIs are used by HLS player, image proxies, SSE, etc.
    if (request.path == "/admin/login"
            or request.path.startswith("/static/")
            or request.path.startswith("/api/")):
        return
    # Check for session auth
    if session.get("remote_auth"):
        return
    # Remote user not authenticated — redirect to login
    return redirect("/admin/login")


@app.route("/admin/login", methods=["GET", "POST"])
def admin_login():
    """Simple password login for remote admin access."""
    if request.method == "POST":
        password = request.form.get("password", "")
        stored = models.get_setting("admin_password") or "family2026"
        if secrets.compare_digest(password, stored):
            session["remote_auth"] = True
            return redirect("/admin")
        return render_template_string(LOGIN_TEMPLATE, error="Wrong password")
    return render_template_string(LOGIN_TEMPLATE, error=None)


LOGIN_TEMPLATE = """<!DOCTYPE html>
<html><head><title>Senior TV Admin</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
body{font-family:'Segoe UI',sans-serif;background:#1a1a2e;color:#f0f0f0;display:flex;
align-items:center;justify-content:center;min-height:100vh;margin:0;}
.login{background:#16213e;padding:40px;border-radius:20px;max-width:400px;width:90%;}
h1{margin:0 0 20px;font-size:28px;}
input{width:100%;padding:14px;font-size:18px;border:2px solid #333;border-radius:10px;
background:#0f3460;color:#fff;margin-bottom:16px;box-sizing:border-box;}
button{width:100%;padding:14px;font-size:18px;background:#e94560;color:#fff;border:none;
border-radius:10px;cursor:pointer;font-weight:700;}
.error{color:#e94560;margin-bottom:12px;}
</style></head><body>
<div class="login">
<h1>Senior TV Admin</h1>
{% if error %}<div class="error">{{ error }}</div>{% endif %}
<form method="POST">
<input type="password" name="password" placeholder="Family password" autofocus>
<button type="submit">Sign In</button>
</form>
</div>
</body></html>"""


# --- Helpers ---

def get_setting_or_default(key):
    val = models.get_setting(key)
    if val is None:
        default = config.DEFAULTS.get(key)
        return str(default) if default is not None else ""
    return val


def get_greeting():
    hour = datetime.now().hour
    if hour < 12:
        period = "Good Morning"
    elif hour < 17:
        period = "Good Afternoon"
    else:
        period = "Good Evening"
    names = get_setting_or_default("greeting_names")
    return f"{period}, {names}!"


def get_weather_summary():
    cached = cache.get("weather_summary")
    if cached:
        return cached
    try:
        lat = get_setting_or_default("weather_lat")
        lon = get_setting_or_default("weather_lon")
        if not lat or not lon:
            return {"temp": "--", "condition": "Not configured", "code": 0}
        unit = get_setting_or_default("weather_unit")
        temp_unit = "fahrenheit" if unit == "fahrenheit" else "celsius"
        resp = requests.get(
            "https://api.open-meteo.com/v1/forecast",
            params={
                "latitude": lat,
                "longitude": lon,
                "current": "temperature_2m,weather_code",
                "temperature_unit": temp_unit,
            },
            timeout=5,
        )
        data = resp.json()
        current = data["current"]
        temp = round(current["temperature_2m"])
        symbol = "°F" if unit == "fahrenheit" else "°C"
        code = current["weather_code"]
        condition = weather_code_to_text(code)
        result = {"temp": f"{temp}{symbol}", "condition": condition, "code": code}
        cache.set("weather_summary", result, ttl=600)  # 10 min
        return result
    except Exception:
        return {"temp": "--", "condition": "Unavailable", "code": -1}


def weather_code_to_text(code):
    mapping = {
        0: "Clear", 1: "Mostly Clear", 2: "Partly Cloudy", 3: "Overcast",
        45: "Foggy", 48: "Foggy", 51: "Light Drizzle", 53: "Drizzle",
        55: "Heavy Drizzle", 61: "Light Rain", 63: "Rain", 65: "Heavy Rain",
        71: "Light Snow", 73: "Snow", 75: "Heavy Snow", 80: "Rain Showers",
        81: "Rain Showers", 82: "Heavy Showers", 95: "Thunderstorm",
    }
    return mapping.get(code, "Unknown")


def weather_code_to_icon(code):
    if code <= 1:
        return "☀️"
    elif code <= 3:
        return "⛅"
    elif code <= 48:
        return "🌫️"
    elif code <= 55:
        return "🌦️"
    elif code <= 65:
        return "🌧️"
    elif code <= 75:
        return "❄️"
    elif code <= 82:
        return "🌧️"
    elif code >= 95:
        return "⛈️"
    return "🌡️"


# ========================================
# TV UI Routes
# ========================================

@app.route("/")
def tv_home():
    greeting = get_greeting()
    weather = get_weather_summary()
    weather_icon = weather_code_to_icon(weather["code"])
    next_pill = get_next_pill_info()
    now = datetime.now()
    date_str = now.strftime("%A, %B %d")
    time_str = now.strftime("%I:%M %p").lstrip("0")

    # Time-of-day content categories (care plan)
    hour = now.hour
    if hour < 14:  # Morning: wake to 2 PM
        time_period = "morning"
        suggested_categories = ["Game Shows", "Morning Shows", "Classic TV"]
        suggested_pluto = ["News + Opinion", "Daytime + Game Shows", "Classic TV"]
    elif hour < 17:  # Afternoon: 2–5 PM
        time_period = "afternoon"
        suggested_categories = ["Westerns", "Classic TV", "Comedy", "Crime & Drama", "Music & Variety"]
        suggested_pluto = ["Westerns", "Classic TV", "Comedy", "Drama", "True Crime"]
    else:  # Evening: 5 PM+
        time_period = "evening"
        suggested_categories = ["Comedy", "Crime & Drama", "Wind Down", "Westerns", "Music & Variety", "Nature"]
        suggested_pluto = ["Comedy", "Classic TV", "Drama", "True Crime", "Westerns"]

    unread_msgs = models.get_unread_count()
    msg_label = f"Messages ({unread_msgs} new)" if unread_msgs > 0 else "Messages"

    # Day info for the left panel
    day_num = now.timetuple().tm_yday
    day_of_year = f"Day {day_num} of {365 + (1 if now.year % 4 == 0 else 0)}"
    # Check if today is a holiday
    today_date = now.strftime("%Y-%m-%d")
    today_events = models.get_upcoming_events(days=1)
    holidays_today = ""
    for ev in today_events:
        if ev["event_date"] == today_date and "🎉" in ev["title"]:
            holidays_today = ev["title"].replace("🎉 ", "")
            break

    menu_items = [
        {"label": "Live TV", "icon": "📺", "url": "/tv/live"},
        {"label": "Movies & Shows", "icon": "🎬", "url": "/tv/plex"},
        {"label": "YouTube", "icon": "▶️", "url": "/tv/youtube"},
        {"label": msg_label, "icon": "💌", "url": "/tv/messages"},
        {"label": "News", "icon": "📰", "url": "/tv/news"},
        {"label": "Weather", "icon": "🌤️", "url": "/tv/weather"},
        {"label": "Calendar", "icon": "📅", "url": "/tv/calendar"},
        {"label": "Photo Frame", "icon": "📷", "url": "/tv/photos"},
    ]

    # Jellyfin recommendations — all genres welcome, the library was curated for them
    jf_movies = []
    jf_shows = []
    jf = _get_jellyfin()
    if jf:
        try:
            resume = jf.get_resume(limit=5)
            libs = jf.get_libraries()
            for lib in libs:
                lib_type = lib.get("type", "")
                try:
                    # Pull extra to account for exclusion filtering
                    items = jf.get_library_items(lib["id"], sort="Random",
                                                 sort_order="Ascending", limit=30)
                    items = [i for i in items if i["id"] not in _excluded_ids][:20]
                    for item in items:
                        if item.get("type") == "series" or lib_type == "tvshows":
                            jf_shows.append(item)
                        else:
                            jf_movies.append(item)
                except Exception:
                    pass
            # Prepend resume items to movies
            jf_movies = resume + jf_movies
        except Exception:
            pass

    # LA news live stream — only show before 3 PM (care plan: no news in evening)
    la_news_video_id = None
    wind_down_video = None
    if hour < 15:
        la_news_video_id = cache.get("la_news_video_id")
        if la_news_video_id is None:
            try:
                r = requests.get("https://www.youtube.com/@abc7/live", timeout=4,
                                 headers={"User-Agent": "Mozilla/5.0"})
                match = re.search(r'"videoId":"([a-zA-Z0-9_-]{11})"', r.text)
                if match and "isLive" in r.text:
                    la_news_video_id = match.group(1)
                    cache.set("la_news_video_id", la_news_video_id, ttl=1800)  # 30 min
            except Exception:
                pass
    else:
        # After 3 PM: embed a calming Wind Down video instead
        wind_down_video = cache.get("wind_down_video")
        if wind_down_video is None:
            try:
                import random as _random
                wd_channels = models.get_youtube_channels(category="Wind Down")
                if wd_channels:
                    ch = _random.choice(wd_channels)
                    feed_url = f"https://www.youtube.com/feeds/videos.xml?channel_id={ch['channel_id']}"
                    feed = feedparser.parse(feed_url)
                    if feed.entries:
                        entry = _random.choice(feed.entries[:10])
                        vid_id = entry.get("yt_videoid", "")
                        if vid_id:
                            wind_down_video = {"video_id": vid_id, "name": ch["name"],
                                               "title": entry.get("title", "")}
                            cache.set("wind_down_video", wind_down_video, ttl=3600)
            except Exception:
                pass

    # Suggested YouTube channels for this time period
    time_youtube = []
    for cat in suggested_categories:
        time_youtube.extend(models.get_youtube_channels(category=cat))

    # Additional category rows
    crime_youtube = models.get_youtube_channels(category="Crime & Drama")
    comedy_youtube = models.get_youtube_channels(category="Comedy")
    local_youtube = (models.get_youtube_channels(category="Local News")
                     + models.get_youtube_channels(category="Morning Shows"))

    # 5-day weather forecast
    forecast = []
    try:
        lat = get_setting_or_default("weather_lat")
        lon = get_setting_or_default("weather_lon")
        unit = get_setting_or_default("weather_unit")
        temp_unit = "fahrenheit" if unit == "fahrenheit" else "celsius"

        forecast_cached = cache.get("forecast_5day")
        if forecast_cached:
            forecast = forecast_cached
        else:
            resp = requests.get(
                "https://api.open-meteo.com/v1/forecast",
                params={
                    "latitude": lat, "longitude": lon,
                    "daily": "weather_code,temperature_2m_max,temperature_2m_min",
                    "temperature_unit": temp_unit, "timezone": "auto", "forecast_days": 5,
                },
                timeout=5,
            )
            data = resp.json()
            for i in range(5):
                day_name = datetime.strptime(data["daily"]["time"][i], "%Y-%m-%d").strftime("%a")
                if i == 0:
                    day_name = "Today"
                forecast.append({
                    "day": day_name,
                    "high": round(data["daily"]["temperature_2m_max"][i]),
                    "low": round(data["daily"]["temperature_2m_min"][i]),
                    "icon": weather_code_to_icon(data["daily"]["weather_code"][i]),
                })
            cache.set("forecast_5day", forecast, ttl=1800)
    except Exception:
        pass

    # Next calendar event
    upcoming = models.get_upcoming_events(days=7)
    next_event = upcoming[0] if upcoming else None

    # Random family photo for home page widget
    home_photo = None
    try:
        import immich_api
        if immich_api.is_configured():
            photos = immich_api.get_random_photos(count=5)
            if photos:
                home_photo = photos[0]
    except Exception:
        pass

    return render_template(
        "tv/home.html",
        greeting=greeting,
        date_str=date_str,
        time_str=time_str,
        weather=weather,
        weather_icon=weather_icon,
        next_pill=next_pill,
        menu_items=menu_items,
        jf_movies=jf_movies[:15],
        jf_shows=jf_shows[:15],
        la_news_video_id=la_news_video_id,
        wind_down_video=wind_down_video,
        next_event=next_event,
        time_period=time_period,
        time_youtube=time_youtube[:10],
        crime_youtube=crime_youtube,
        comedy_youtube=comedy_youtube,
        local_youtube=local_youtube[:8],
        suggested_pluto=suggested_pluto,
        unread_msgs=unread_msgs,
        day_of_year=day_of_year,
        holidays_today=holidays_today,
        forecast=forecast,
        home_photo=home_photo,
        first_boot=not get_setting_or_default("greeting_names"),
    )


@app.route("/tv/weather")
def tv_weather():
    try:
        lat = get_setting_or_default("weather_lat")
        lon = get_setting_or_default("weather_lon")
        unit = get_setting_or_default("weather_unit")
        temp_unit = "fahrenheit" if unit == "fahrenheit" else "celsius"
        resp = requests.get(
            "https://api.open-meteo.com/v1/forecast",
            params={
                "latitude": lat,
                "longitude": lon,
                "current": "temperature_2m,weather_code,relative_humidity_2m,wind_speed_10m",
                "daily": "weather_code,temperature_2m_max,temperature_2m_min",
                "temperature_unit": temp_unit,
                "wind_speed_unit": "mph",
                "timezone": "auto",
                "forecast_days": 5,
            },
            timeout=10,
        )
        data = resp.json()
        symbol = "°F" if unit == "fahrenheit" else "°C"

        current = {
            "temp": round(data["current"]["temperature_2m"]),
            "condition": weather_code_to_text(data["current"]["weather_code"]),
            "icon": weather_code_to_icon(data["current"]["weather_code"]),
            "humidity": data["current"]["relative_humidity_2m"],
            "wind": round(data["current"]["wind_speed_10m"]),
            "symbol": symbol,
        }

        forecast = []
        for i in range(5):
            day_name = datetime.strptime(data["daily"]["time"][i], "%Y-%m-%d").strftime("%A")
            if i == 0:
                day_name = "Today"
            forecast.append({
                "day": day_name,
                "high": round(data["daily"]["temperature_2m_max"][i]),
                "low": round(data["daily"]["temperature_2m_min"][i]),
                "icon": weather_code_to_icon(data["daily"]["weather_code"][i]),
                "condition": weather_code_to_text(data["daily"]["weather_code"][i]),
                "symbol": symbol,
            })

        return render_template("tv/weather.html", current=current, forecast=forecast)
    except Exception as e:
        return render_template("tv/weather.html", current=None, forecast=[], error=str(e))


@app.route("/tv/news")
def tv_news():
    """News page with live video streams and headlines."""
    # YouTube live news streams — we scrape the current video ID from channel /live pages
    live_streams = []
    yt_channels = [
        ("ABC News", "https://www.youtube.com/@ABCNews/live"),
        ("NBC News NOW", "https://www.youtube.com/@NBCNews/live"),
        ("CBS News", "https://www.youtube.com/@CBSNews/live"),
        ("FOX 11 Los Angeles", "https://www.youtube.com/@FOX11LosAngeles/live"),
    ]
    for name, url in yt_channels:
        try:
            r = requests.get(url, timeout=5, headers={"User-Agent": "Mozilla/5.0"})
            match = re.search(r'"videoId":"([a-zA-Z0-9_-]{11})"', r.text)
            if match:
                live_streams.append({
                    "name": name,
                    "video_id": match.group(1),
                    "type": "youtube",
                })
        except Exception:
            continue

    # Also include Pluto TV news channels for quick access
    pluto_news = []
    try:
        import pluto_tv
        channels, _ = pluto_tv.get_channels(category_filter="News + Opinion")
        for ch in channels[:6]:
            pluto_news.append({
                "name": ch["name"],
                "id": ch["id"],
                "logo": ch.get("logo", ""),
                "current_program": ch.get("current_program"),
            })
    except Exception:
        pass

    # RSS headlines as supplementary
    feeds_str = get_setting_or_default("news_feeds")
    feed_urls = [u.strip() for u in feeds_str.split(",") if u.strip()]
    articles = []
    for url in feed_urls:
        try:
            feed = feedparser.parse(url)
            for entry in feed.entries[:8]:
                articles.append({
                    "title": entry.get("title", ""),
                    "summary": entry.get("summary", "")[:200],
                    "source": feed.feed.get("title", "News"),
                })
        except Exception:
            continue

    return render_template("tv/news.html", live_streams=live_streams,
                           pluto_news=pluto_news, articles=articles[:10])


@app.route("/tv/news/youtube/<video_id>")
def tv_news_youtube(video_id):
    """Watch a YouTube live news stream."""
    # Sanitize video_id
    if not re.match(r'^[a-zA-Z0-9_-]{11}$', video_id):
        return redirect("/tv/news")
    return render_template("tv/news_player.html", video_id=video_id)


@app.route("/tv/calendar")
def tv_calendar():
    import calendar as cal_mod
    view = request.args.get("view", "daily")
    now = datetime.now()
    events = models.get_upcoming_events(days=60)

    if view == "daily":
        today_str = now.strftime("%A, %B %d, %Y")
        today_date = now.strftime("%Y-%m-%d")
        today_events = [e for e in events if e["event_date"] == today_date]
        # Build hourly timeline 6am to 10pm
        day_hours = []
        for h in range(6, 23):
            ampm = f"{h % 12 or 12}:00 {'AM' if h < 12 else 'PM'}"
            hour_events = [e for e in today_events if e.get("event_time", "").startswith(f"{h:02d}:")]
            day_hours.append({"label": ampm, "events": hour_events})
        # Next 5 days
        from datetime import timedelta as _td
        upcoming_days = []
        for d in range(1, 6):
            day = now + _td(days=d)
            day_date = day.strftime("%Y-%m-%d")
            day_events = [e for e in events if e["event_date"] == day_date]
            upcoming_days.append({
                "label": day.strftime("%A, %B %d"),
                "events": day_events,
            })

        return render_template("tv/calendar.html", view="daily", today_str=today_str,
                               day_hours=day_hours, events=events, upcoming_days=upcoming_days)

    elif view == "monthly":
        month_name = now.strftime("%B")
        year = now.year
        month = now.month
        weekday_labels = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"]

        # Build month grid
        first_day = datetime(year, month, 1)
        first_weekday = (first_day.weekday() + 1) % 7  # 0=Sun
        days_in_month = cal_mod.monthrange(year, month)[1]
        event_dates = {e["event_date"] for e in events}

        month_days = []
        for _ in range(first_weekday):
            month_days.append({"num": None, "is_today": False, "has_event": False})
        for d in range(1, days_in_month + 1):
            date_str = f"{year}-{month:02d}-{d:02d}"
            month_days.append({
                "num": d,
                "is_today": d == now.day,
                "has_event": date_str in event_dates,
            })

        return render_template("tv/calendar.html", view="monthly", month_name=month_name,
                               year=year, weekday_labels=weekday_labels, month_days=month_days,
                               events=events)
    else:
        events = models.get_upcoming_events(days=365)
        return render_template("tv/calendar.html", view="upcoming", events=events)


# --- Plex Integration ---

def _get_jellyfin():
    """Get a JellyfinAPI instance from settings."""
    from jellyfin_api import JellyfinAPI
    url = get_setting_or_default("jellyfin_url")
    api_key = get_setting_or_default("jellyfin_api_key")
    user_id = get_setting_or_default("jellyfin_user_id")
    if not url or not api_key or not user_id:
        return None
    return JellyfinAPI(url, api_key, user_id)


@app.route("/tv/plex")
def tv_plex():
    """Media library browser (Jellyfin-powered)."""
    jf = _get_jellyfin()
    if not jf:
        return render_template("tv/plex.html", libraries=[], on_deck=[], recent=[],
                               error="Media server not configured. Ask your family member to set it up in the admin panel.")

    try:
        libraries = jf.get_libraries()
        on_deck = jf.get_resume(limit=10)
        recent = jf.get_latest(limit=20)
        return render_template("tv/plex.html", libraries=libraries, on_deck=on_deck, recent=recent, error=None)
    except Exception as e:
        return render_template("tv/plex.html", libraries=[], on_deck=[], recent=[], error=str(e))


@app.route("/tv/plex/library/<library_id>")
def tv_plex_library(library_id):
    """Browse items in a Jellyfin library with genre filtering and sorting."""
    jf = _get_jellyfin()
    if not jf:
        return redirect("/tv/plex")

    genre = request.args.get("genre")
    sort = request.args.get("sort", "SortName")
    try:
        page = int(request.args.get("page", 0))
    except (ValueError, TypeError):
        page = 0
    per_page = 40

    SORT_OPTIONS = [
        ("SortName", "Ascending", "A - Z"),
        ("SortName", "Descending", "Z - A"),
        ("DateCreated", "Descending", "Recently Added"),
        ("CommunityRating", "Descending", "Top Rated"),
        ("ProductionYear", "Descending", "Newest"),
        ("ProductionYear", "Ascending", "Oldest"),
        ("Random", "Ascending", "Surprise Me"),
    ]
    sort_order = "Ascending"
    sort_label = "A - Z"
    for s_key, s_order, s_label in SORT_OPTIONS:
        if s_key == sort:
            sort_order = request.args.get("order", s_order)
            sort_label = s_label
            break

    try:
        genres = jf.get_genres(library_id)
        items = jf.get_library_items(library_id, sort=sort, sort_order=sort_order,
                                     genre=genre, limit=per_page, start=page * per_page)
        libraries = jf.get_libraries()
        lib_name = next((lib["title"] for lib in libraries if lib["id"] == library_id), "Library")
        has_more = len(items) == per_page

        return render_template("tv/plex_browse.html", items=items, library_name=lib_name,
                               library_id=library_id, genres=genres, selected_genre=genre,
                               sort_options=SORT_OPTIONS, selected_sort=sort, sort_label=sort_label,
                               page=page, has_more=has_more)
    except Exception as e:
        return render_template("tv/plex_browse.html", items=[], library_name="Library",
                               library_id=library_id, genres=[], selected_genre=None,
                               sort_options=[], selected_sort="SortName", sort_label="A-Z",
                               page=0, has_more=False, error=str(e))


@app.route("/tv/plex/daily")
def tv_plex_daily():
    """Today's 20 movies — different every day."""
    jf = _get_jellyfin()
    if not jf:
        return redirect("/tv/plex")

    try:
        libs = jf.get_libraries()
        movies_lib = next((lib for lib in libs if lib["type"] == "movies"), None)
        if not movies_lib:
            return redirect("/tv/plex")
        movies = jf.get_daily_picks(movies_lib["id"], count=20)
        from datetime import date
        today_str = date.today().strftime("%A, %B %d")
        return render_template("tv/plex_daily.html", movies=movies, today_str=today_str)
    except Exception as e:
        return render_template("tv/plex_daily.html", movies=[], today_str="Today", error=str(e))


@app.route("/tv/plex/shuffle/<item_id>")
def tv_plex_shuffle(item_id):
    """Play a random episode from a TV show."""
    jf = _get_jellyfin()
    if not jf:
        return redirect("/tv/plex")

    try:
        episode = jf.get_random_episode(item_id)
        if episode:
            stream_url = jf.get_stream_url(episode["id"])
            transcode_url = jf.get_transcode_url(episode["id"])
            subtitle_url = jf.get_subtitle_url(episode["id"])
            return render_template("tv/player.html", item=episode, stream_url=stream_url,
                                   transcode_url=transcode_url, subtitle_url=subtitle_url,
                                   item_id=episode["id"])
        return redirect(f"/tv/plex/show/{item_id}")
    except Exception:
        return redirect(f"/tv/plex/show/{item_id}")


@app.route("/tv/plex/show/<item_id>")
def tv_plex_show(item_id):
    """Show seasons and episodes for a TV show."""
    jf = _get_jellyfin()
    if not jf:
        return redirect("/tv/plex")

    try:
        show = jf.get_item(item_id)
        seasons = jf.get_seasons(item_id)
        selected_season = request.args.get("season")
        episodes = []
        season_id = None
        if seasons:
            season_id = selected_season or seasons[0]["id"]
            episodes = jf.get_episodes(item_id, season_id)
        return render_template("tv/plex_show.html", show=show, seasons=seasons,
                               episodes=episodes, selected_season=season_id)
    except Exception as e:
        return render_template("tv/plex_show.html", show=None, seasons=[], episodes=[], selected_season=None, error=str(e))


@app.route("/tv/plex/play/<item_id>")
def tv_plex_play(item_id):
    """Play a Jellyfin item in our built-in player."""
    jf = _get_jellyfin()
    if not jf:
        return redirect("/tv/plex")

    try:
        item = jf.get_item(item_id)
        stream_url = jf.get_stream_url(item_id)
        transcode_url = jf.get_transcode_url(item_id)
        subtitle_url = jf.get_subtitle_url(item_id)
        jf.report_playback_start(item_id)
        return render_template("tv/player.html", item=item, stream_url=stream_url,
                               transcode_url=transcode_url, subtitle_url=subtitle_url,
                               item_id=item_id)
    except Exception:
        return redirect("/tv/plex")


# --- Family Messages ---

@app.route("/tv/messages")
def tv_messages():
    """View family messages on the TV."""
    messages = models.get_messages(limit=20)
    unread = models.get_unread_count()
    return render_template("tv/messages.html", messages=messages, unread=unread)


@app.route("/tv/messages/<int:msg_id>")
def tv_message_view(msg_id):
    """View a single message full-screen."""
    msg = models.get_message(msg_id)
    if not msg:
        return redirect("/tv/messages")
    models.mark_message_read(msg_id)
    return render_template("tv/message_view.html", message=msg)


# --- Pluto TV Live Channels ---

@app.route("/tv/live")
def tv_live():
    """Live TV channel guide powered by Pluto TV."""
    import pluto_tv
    from urllib.parse import quote
    category = request.args.get("category")
    channels, error = pluto_tv.get_channels(category_filter=category)
    categories, _ = pluto_tv.get_categories()
    for cat in categories:
        cat["slug"] = quote(cat["name"], safe="")
    return render_template("tv/live.html", channels=channels, categories=categories,
                           selected_category=category, error=error)


@app.route("/api/live-channels")
def api_live_channels():
    import pluto_tv
    category = request.args.get("category") or None
    channels, error = pluto_tv.get_channels(category_filter=category)
    if error:
        return jsonify({"error": str(error), "channels": []})
    result = []
    for ch in channels:
        prog = ch.get("current_program")
        result.append({
            "id": ch["id"],
            "name": ch["name"],
            "logo": ch.get("logo", ""),
            "number": ch.get("number", 0),
            "current_program": {"title": prog["title"], "description": prog.get("description", "")} if prog else None,
        })
    return jsonify({"channels": result})


@app.route("/tv/live/play/<channel_id>")
def tv_live_play(channel_id):
    """Play a live Pluto TV channel."""
    import pluto_tv
    # Clear cached channels to get fresh stream URLs with current session
    cache.clear("pluto_all_channels")
    channel, error = pluto_tv.get_channel_by_id(channel_id)
    if not channel:
        return redirect("/tv/live")
    return render_template("tv/live_player.html", channel=channel)


@app.route("/api/pluto-stream/<channel_id>")
def pluto_stream_master(channel_id):
    """Proxy Pluto TV master m3u8, rewriting URLs to go through our proxy."""
    import pluto_tv
    channel, error = pluto_tv.get_channel_by_id(channel_id)
    if not channel:
        return "", 404
    try:
        stream_url = channel["stream_url"]
        resp = requests.get(stream_url, timeout=15)
        if resp.status_code in (401, 403) or resp.status_code >= 500:
            # Session may have expired — retry with fresh token
            pluto_tv.invalidate_session()
            cache.clear("pluto_all_channels")
            channel, error = pluto_tv.get_channel_by_id(channel_id)
            if not channel:
                return "", 404
            resp = requests.get(channel["stream_url"], timeout=15)
        if resp.status_code != 200:
            return "", resp.status_code
        base_url = stream_url.rsplit("/", 1)[0] + "/"

        rewritten = _rewrite_m3u8(resp.text, base_url)
        return Response(rewritten, mimetype="application/x-mpegurl",
                        headers={"Access-Control-Allow-Origin": "*"})
    except Exception:
        return "", 502


def _rewrite_m3u8(content, base_url):
    """Rewrite m3u8 playlist URLs to go through our proxy."""
    from urllib.parse import urljoin, quote
    lines = content.split("\n")
    rewritten = []
    for line in lines:
        stripped = line.strip()
        if stripped and not stripped.startswith("#"):
            if stripped.startswith("http"):
                abs_url = stripped
            else:
                abs_url = urljoin(base_url, stripped)
            rewritten.append(f"/api/pluto-proxy?url={quote(abs_url, safe='')}")
        elif stripped.startswith("#") and "URI=" in stripped:
            # Rewrite URI= in #EXT tags (subtitles, etc.)
            def rewrite_uri(m):
                uri = m.group(1)
                if uri.startswith("http"):
                    abs_uri = uri
                else:
                    abs_uri = urljoin(base_url, uri)
                return f'URI="/api/pluto-proxy?url={quote(abs_uri, safe="")}"'
            rewritten.append(re.sub(r'URI="([^"]*)"', rewrite_uri, stripped))
        else:
            rewritten.append(line)
    return "\n".join(rewritten)


@app.route("/api/pluto-proxy")
def pluto_proxy():
    """Proxy any Pluto TV URL (segments, sub-playlists) to bypass CORS."""
    url = request.args.get("url")
    if not url or not any(d in url for d in ("pluto.tv", "plutotv.com", "plutotv.net", "pluto-prod-",
                                              "akamaized.net", "cloudfront.net", "dai.google.com")):
        return "", 403
    try:
        resp = requests.get(url, timeout=15, stream=True)
        if resp.status_code in (401, 403):
            # Token expired mid-stream — invalidate so next master m3u8 gets a fresh session
            import pluto_tv
            pluto_tv.invalidate_session()
            return "", resp.status_code
        if resp.status_code != 200:
            return "", resp.status_code
        content_type = resp.headers.get("content-type", "application/octet-stream")

        if "mpegurl" in content_type or ".m3u8" in url:
            base_url = url.rsplit("/", 1)[0] + "/"
            rewritten = _rewrite_m3u8(resp.text, base_url)
            return Response(rewritten, mimetype="application/x-mpegurl",
                            headers={"Access-Control-Allow-Origin": "*"})
        else:
            return Response(resp.content, mimetype=content_type,
                            headers={"Access-Control-Allow-Origin": "*"})
    except Exception:
        return "", 502


# --- YouTube ---

@app.route("/tv/youtube")
def tv_youtube():
    """YouTube viewer with curated channels."""
    yt_channels = models.get_youtube_channels()
    # Group by category
    categories = {}
    for ch in yt_channels:
        cat = ch.get("category", "Entertainment")
        if cat not in categories:
            categories[cat] = []
        categories[cat].append(ch)

    # Also add local live streams
    local_streams = _get_local_live_streams()

    return render_template("tv/youtube.html", categories=categories,
                           local_streams=local_streams, channels=yt_channels)


def _get_local_live_streams():
    """Get current live YouTube streams for local LA/SD stations."""
    streams = []
    local_channels = [
        ("ABC 7 Los Angeles", "https://www.youtube.com/@abc7/live"),
        ("FOX 11 Los Angeles", "https://www.youtube.com/@FOX11LosAngeles/live"),
        ("NBC Los Angeles", "https://www.youtube.com/@ABORABLE/live"),
        ("CBS 8 San Diego", "https://www.youtube.com/@CBS8/live"),
    ]
    for name, url in local_channels:
        try:
            r = requests.get(url, timeout=4, headers={"User-Agent": "Mozilla/5.0"})
            match = re.search(r'"videoId":"([a-zA-Z0-9_-]{11})"', r.text)
            if match and "isLive" in r.text:
                streams.append({"name": name, "video_id": match.group(1)})
        except Exception:
            continue
    return streams


@app.route("/tv/youtube/channel/<channel_id>")
def tv_youtube_channel(channel_id):
    """Browse a YouTube channel's recent videos."""
    # Fetch channel page for recent uploads
    ch_record = None
    yt_channels = models.get_youtube_channels()
    for ch in yt_channels:
        if ch["channel_id"] == channel_id:
            ch_record = ch
            break

    channel_name = ch_record["name"] if ch_record else "YouTube"

    # Fetch recent videos via RSS (no API key needed)
    videos = []
    try:
        feed_url = f"https://www.youtube.com/feeds/videos.xml?channel_id={channel_id}"
        feed = feedparser.parse(feed_url)
        for entry in feed.entries[:20]:
            # Try yt:videoId tag first, then URL param
            vid_id = entry.get("yt_videoid", "")
            if not vid_id:
                vid_match = re.search(r'[?&]v=([a-zA-Z0-9_-]{11})', entry.get("link", ""))
                vid_id = vid_match.group(1) if vid_match else ""
            thumb = f"https://i.ytimg.com/vi/{vid_id}/mqdefault.jpg" if vid_id else ""
            videos.append({
                "title": entry.get("title", ""),
                "video_id": vid_id,
                "thumbnail": thumb,
                "published": entry.get("published", ""),
            })
    except Exception:
        pass

    return render_template("tv/youtube_channel.html", channel_name=channel_name,
                           channel_id=channel_id, videos=videos)


@app.route("/tv/youtube/watch/<video_id>")
def tv_youtube_watch(video_id):
    """Watch a YouTube video."""
    if not re.match(r'^[a-zA-Z0-9_-]{11}$', video_id):
        return redirect("/tv/youtube")
    return render_template("tv/youtube_player.html", video_id=video_id)


# --- YouTube Admin ---

@app.route("/admin/youtube")
def admin_youtube():
    channels = models.get_youtube_channels()
    return render_template("admin/youtube.html", channels=channels)


@app.route("/admin/youtube/new", methods=["GET", "POST"])
def admin_youtube_new():
    if request.method == "POST":
        data = {
            "name": request.form["name"],
            "channel_id": request.form["channel_id"],
            "description": request.form.get("description", ""),
            "thumbnail_url": request.form.get("thumbnail_url", ""),
            "category": request.form.get("category", "Entertainment"),
            "sort_order": _safe_int(request.form.get("sort_order"), 0),
        }
        models.create_youtube_channel(data)
        return redirect("/admin/youtube")
    return render_template("admin/youtube_form.html", channel=None)


@app.route("/admin/youtube/<int:ch_id>/edit", methods=["GET", "POST"])
def admin_youtube_edit(ch_id):
    ch = models.get_youtube_channel(ch_id)
    if not ch:
        return redirect("/admin/youtube")
    if request.method == "POST":
        data = {
            "name": request.form["name"],
            "channel_id": request.form["channel_id"],
            "description": request.form.get("description", ""),
            "thumbnail_url": request.form.get("thumbnail_url", ""),
            "category": request.form.get("category", "Entertainment"),
            "sort_order": _safe_int(request.form.get("sort_order"), 0),
        }
        models.update_youtube_channel(ch_id, data)
        return redirect("/admin/youtube")
    return render_template("admin/youtube_form.html", channel=ch)


@app.route("/admin/youtube/<int:ch_id>/delete", methods=["POST"])
def admin_youtube_delete(ch_id):
    models.delete_youtube_channel(ch_id)
    return redirect("/admin/youtube")


# --- SSE endpoint for pill reminders ---

@app.route("/events")
def sse_events():
    def stream():
        while True:
            try:
                event = reminder_queue.get(timeout=30)
                yield f"data: {json.dumps(event)}\n\n"
            except Exception:
                yield ": keepalive\n\n"

    return Response(stream(), mimetype="text/event-stream",
                    headers={"Cache-Control": "no-cache", "X-Accel-Buffering": "no"})


@app.route("/api/acknowledge", methods=["POST"])
def api_acknowledge():
    data = request.get_json()
    reminder_id = data.get("reminder_id")
    if reminder_id and acknowledge_reminder(reminder_id):
        return jsonify({"status": "ok"})
    return jsonify({"status": "not_found"}), 404


@app.route("/api/log-activity", methods=["POST"])
def api_log_activity():
    """Log playback/navigation activity from the TV client."""
    data = request.get_json() or {}
    models.log_activity(
        activity_type=data.get("type", "unknown"),
        item_id=data.get("item_id"),
        item_title=data.get("title"),
        item_type=data.get("item_type"),
        duration_seconds=data.get("duration"),
    )
    return jsonify({"status": "logged"})


@app.route("/api/log-activity-stop", methods=["POST"])
def api_log_activity_stop():
    """Log playback stop with duration."""
    data = request.get_json() or {}
    models.log_activity_stop(
        item_id=data.get("item_id"),
        duration_seconds=data.get("duration"),
    )
    return jsonify({"status": "logged"})


@app.route("/api/log-remote", methods=["POST"])
def api_log_remote():
    """Log CEC remote button presses."""
    data = request.get_json() or {}
    models.log_remote_button(
        cec_code=data.get("cec_code"),
        x_key=data.get("key"),
        description=data.get("description"),
    )
    return jsonify({"status": "logged"})


# ========================================
# Admin Panel Routes
# ========================================

@app.route("/admin")
def admin_dashboard():
    pills = models.get_pills()
    for pill in pills:
        try:
            pill["schedule_times_display"] = ", ".join(json.loads(pill["schedule_times"]))
        except (json.JSONDecodeError, TypeError):
            pill["schedule_times_display"] = "—"
    events = models.get_upcoming_events(days=14)
    settings = models.get_all_settings()
    last_activity = models.get_last_activity_time()

    # Presence inference from last activity
    presence = None
    mins_ago = None
    if last_activity:
        try:
            last_dt = datetime.strptime(last_activity[:19], "%Y-%m-%d %H:%M:%S")
            mins_ago = int((datetime.now() - last_dt).total_seconds() / 60)
            if mins_ago < 30:
                presence = {"label": f"Active ({mins_ago}m ago)", "color": "#4caf50"}
            elif mins_ago < 120:
                presence = {"label": f"Idle ({mins_ago}m ago)", "color": "#ff9800"}
            else:
                hours = mins_ago // 60
                presence = {"label": f"Away ({hours}h ago)", "color": "#f44336"}
        except Exception:
            pass

    # System metrics
    system_metrics = {}
    try:
        import psutil
        system_metrics = {
            "cpu_percent": psutil.cpu_percent(interval=0.5),
            "mem_total_gb": round(psutil.virtual_memory().total / (1024**3), 1),
            "mem_used_gb": round(psutil.virtual_memory().used / (1024**3), 1),
            "mem_percent": psutil.virtual_memory().percent,
            "disk_total_gb": round(shutil.disk_usage("/").total / (1024**3)),
            "disk_used_gb": round(shutil.disk_usage("/").used / (1024**3)),
            "disk_percent": round(shutil.disk_usage("/").used / shutil.disk_usage("/").total * 100, 1),
            "uptime": "",
            "containers_running": 0,
        }
        uptime_sec = int(psutil.boot_time())
        boot = datetime.fromtimestamp(uptime_sec)
        delta = datetime.now() - boot
        days = delta.days
        hours = delta.seconds // 3600
        system_metrics["uptime"] = f"{days}d {hours}h" if days else f"{hours}h {(delta.seconds % 3600) // 60}m"
        try:
            result = subprocess.run(["docker", "ps", "-q"], capture_output=True, text=True, timeout=3)
            system_metrics["containers_running"] = len(result.stdout.strip().split("\n")) if result.stdout.strip() else 0
        except Exception:
            pass
    except Exception:
        pass

    # TV room presence from smart home
    tv_presence = None
    try:
        from smart_home import get_presence
        p = get_presence()
        tv_presence = dict(p)
        if p["last_seen"]:
            tv_presence["last_seen_str"] = p["last_seen"].strftime("%I:%M %p")
        else:
            tv_presence["last_seen_str"] = "Not yet today"
        mins = int(p["today_minutes"])
        tv_presence["today_hours"] = f"{mins // 60}h {mins % 60}m" if mins >= 60 else f"{mins}m"
    except Exception:
        pass

    # Recent doorbell events from Frigate
    doorbell_events = []
    frigate_url = get_setting_or_default("frigate_url")
    if frigate_url:
        try:
            from smart_home import frigate_get_events
            raw_events = frigate_get_events(frigate_url, camera="front_door", label="person", limit=4)
            if raw_events:
                for evt in raw_events:
                    ts = evt.get("start_time", 0)
                    try:
                        evt_dt = datetime.fromtimestamp(ts)
                        evt_mins = int((datetime.now() - evt_dt).total_seconds() / 60)
                        if evt_mins < 60:
                            time_str = f"{evt_mins}m ago"
                        elif evt_mins < 1440:
                            time_str = f"{evt_mins // 60}h ago"
                        else:
                            time_str = evt_dt.strftime("%b %d, %I:%M %p")
                    except Exception:
                        time_str = "Unknown"
                    doorbell_events.append({
                        "id": evt.get("id", ""),
                        "camera": evt.get("camera", "unknown"),
                        "time": time_str,
                    })
        except Exception:
            pass

    # Pill adherence
    pill_adherence = models.get_pill_adherence_today()
    pill_adherence = [e for e in pill_adherence if "stretch" not in e.get("pill_name", "").lower()]
    pill_summary = {"taken": 0, "missed": 0, "pending": 0, "total": 0}
    for entry in pill_adherence:
        pill_summary[entry["status"]] += 1
        pill_summary["total"] += 1
    pill_adherence.sort(key=lambda x: {"pending": 0, "missed": 1, "taken": 2}.get(x["status"], 3))

    # New data for care dashboard
    from scheduler import get_next_pill_info
    next_pill = get_next_pill_info()
    unread_messages = models.get_unread_count()
    todays_birthdays = models.get_todays_birthdays()
    recent_activity = models.get_activity_logs(days=1, limit=3)
    weather = get_weather_summary()

    # Care status banner
    if tv_presence and tv_presence.get("occupied"):
        care_status = {"message": "Don & Colleen are watching TV", "color": "#4caf50", "icon": "📺"}
    elif presence and "Active" in presence.get("label", ""):
        care_status = {"message": presence["label"], "color": "#4caf50", "icon": "✅"}
    elif presence and "Idle" in presence.get("label", ""):
        care_status = {"message": presence["label"], "color": "#ff9800", "icon": "💤"}
    else:
        msg = presence["label"] if presence else "No recent activity"
        care_status = {"message": msg, "color": "#f44336", "icon": "⚠️"}

    # System health (simplified for banner)
    system_ok = all([
        system_metrics.get("cpu_percent", 0) < 90,
        system_metrics.get("mem_percent", 0) < 90,
        system_metrics.get("disk_percent", 0) < 90,
    ])

    return render_template("admin/dashboard.html",
                           pills=pills, events=events, settings=settings,
                           pill_adherence=pill_adherence, pill_summary=pill_summary,
                           care_status=care_status, weather=weather,
                           next_pill=next_pill, unread_messages=unread_messages,
                           todays_birthdays=todays_birthdays,
                           recent_activity=recent_activity,
                           tv_presence=tv_presence,
                           doorbell_events=doorbell_events,
                           system_metrics=system_metrics, system_ok=system_ok,
                           current_year=datetime.now().year)


@app.route("/admin/activity")
def admin_activity():
    """View activity and remote button logs."""
    logs = models.get_activity_logs(days=7)
    return render_template("admin/activity.html", logs=logs)


@app.route("/admin/cameras")
def admin_cameras():
    """Live camera view with snapshots from Frigate."""
    cameras = []
    try:
        resp = requests.get("http://localhost:5001/api/stats", timeout=5)
        if resp.ok:
            stats = resp.json()
            config_resp = requests.get("http://localhost:5001/api/config", timeout=5)
            cam_config = config_resp.json().get("cameras", {}) if config_resp.ok else {}
            for name, info in sorted(stats.get("cameras", {}).items()):
                detect = cam_config.get(name, {}).get("detect", {})
                cameras.append({
                    "name": name,
                    "camera_fps": round(info.get("camera_fps", 0), 1),
                    "detection_fps": round(info.get("detection_fps", 0), 1),
                    "width": detect.get("width", "?"),
                    "height": detect.get("height", "?"),
                    "fps": detect.get("fps", "?"),
                })
            # Front door first, then tv_room, then rest alphabetically
            priority = {"front_door": 0, "tv_room": 1}
            cameras.sort(key=lambda c: (priority.get(c["name"], 99), c["name"]))
    except Exception:
        pass

    # Saved camera snapshots (check on loved ones)
    # Show latest 4 per camera, front_door and tv_room first
    saved_snaps = []
    snap_dir = os.path.join(config.BASE_DIR, "static", "camera_snaps")
    if os.path.isdir(snap_dir):
        by_camera = {}
        for f in sorted(os.listdir(snap_dir), reverse=True):
            if f.endswith(".jpg"):
                parts = f.replace(".jpg", "").split("_")
                # Format: camera_name_YYYYMMDD_HHMMSS.jpg
                if len(parts) >= 3:
                    cam_name = "_".join(parts[:-2])
                    if cam_name not in by_camera:
                        by_camera[cam_name] = []
                    if len(by_camera[cam_name]) >= 4:
                        continue
                    ts = parts[-2] + "_" + parts[-1]
                    try:
                        from datetime import datetime as _dt
                        dt = _dt.strptime(ts, "%Y%m%d_%H%M%S")
                        time_str = dt.strftime("%b %d, %I:%M %p")
                    except Exception:
                        time_str = ts
                    by_camera[cam_name].append({"file": f, "camera": cam_name, "time": time_str})
        # Order: front_door first, tv_room second, rest alphabetically
        priority = {"front_door": 0, "tv_room": 1}
        for cam in sorted(by_camera, key=lambda c: (priority.get(c, 99), c)):
            saved_snaps.extend(by_camera[cam])

    return render_template("admin/cameras.html", cameras=cameras, saved_snaps=saved_snaps)


@app.route("/admin/cameras/snapshot/<camera_name>")
def admin_camera_snapshot(camera_name):
    """Proxy camera snapshot from Frigate."""
    if not re.match(r'^[a-z_]+$', camera_name):
        return "", 400
    try:
        resp = requests.get(
            f"http://localhost:5001/api/{camera_name}/latest.jpg",
            params={"h": 480},
            timeout=5,
        )
        if resp.ok:
            return Response(resp.content, mimetype="image/jpeg",
                            headers={"Cache-Control": "no-cache"})
    except Exception:
        pass
    return "", 404


@app.route("/admin/services")
def admin_services():
    """Docker service management page."""
    # Build service URLs dynamically based on request host
    host_ip = request.host.split(":")[0]
    local = _is_local_request()
    services = [
        {"name": "Jellyfin", "icon": "🎬", "url": f"http://{host_ip}:8096" if local else "/jellyfin/", "check": "http://localhost:8096", "port": "8096", "detail": "Media server — movies, shows, music"},
        {"name": "Immich", "icon": "📸", "url": f"http://{host_ip}:2283" if local else "/immich/", "check": "http://localhost:2283", "port": "2283", "detail": "Photo library — family photos"},
        {"name": "Home Assistant", "icon": "🏠", "url": f"http://{host_ip}:8123" if local else "/ha/", "check": "http://localhost:8123", "port": "8123", "detail": "Smart home — TV control, automations"},
    ]
    for svc in services:
        try:
            resp = requests.get(svc["check"], timeout=3, allow_redirects=True)
            svc["ok"] = resp.status_code < 500
        except Exception:
            svc["ok"] = False

    # Docker container stats
    docker_stats = []
    try:
        result = subprocess.run(
            ["docker", "stats", "--no-stream", "--format", "{{.Name}}\t{{.Status}}\t{{.CPUPerc}}\t{{.MemUsage}}"],
            capture_output=True, text=True, timeout=10,
        )
        # Fallback to docker ps if stats fails
        if not result.stdout.strip():
            result = subprocess.run(
                ["docker", "ps", "--format", "{{.Names}}\t{{.Status}}\t-\t-"],
                capture_output=True, text=True, timeout=5,
            )
        for line in result.stdout.strip().split("\n"):
            if line:
                parts = line.split("\t")
                if len(parts) >= 4:
                    docker_stats.append({
                        "name": parts[0],
                        "status": parts[1] if len(parts) > 1 else "?",
                        "cpu": parts[2] if len(parts) > 2 else "?",
                        "mem": parts[3] if len(parts) > 3 else "?",
                    })
    except Exception:
        pass

    return render_template("admin/services.html", services=services, docker_stats=docker_stats)


@app.route("/admin/tv-view")
def admin_tv_view():
    """Live TV view and screenshot history."""
    ss_dir = os.path.join(config.BASE_DIR, "static", "screenshots")
    screenshots = []
    if os.path.isdir(ss_dir):
        for f in sorted(os.listdir(ss_dir), reverse=True):
            if f.startswith("screen_") and f.endswith(".png"):
                # Parse timestamp from filename: screen_20260326_065011.png
                ts = f.replace("screen_", "").replace(".png", "")
                try:
                    from datetime import datetime as _dt
                    dt = _dt.strptime(ts, "%Y%m%d_%H%M%S")
                    time_str = dt.strftime("%b %d, %I:%M %p")
                except Exception:
                    time_str = ts
                screenshots.append({"file": f, "time": time_str})
    return render_template("admin/tv_view.html", screenshots=screenshots[:50])


@app.route("/api/screenshot", methods=["POST"])
def api_take_screenshot():
    """Capture what the kiosk Chrome is displaying via DevTools Protocol."""
    import base64
    import urllib.request
    from datetime import datetime as _dt
    ss_dir = os.path.join(config.BASE_DIR, "static", "screenshots")
    os.makedirs(ss_dir, exist_ok=True)
    ts = _dt.now().strftime("%Y%m%d_%H%M%S")
    filename = f"screen_{ts}.png"
    filepath = os.path.join(ss_dir, filename)
    try:
        # Get the first page from Chrome DevTools
        tabs_raw = urllib.request.urlopen("http://127.0.0.1:9222/json", timeout=5).read()
        tabs = json.loads(tabs_raw)
        ws_url = None
        for tab in tabs:
            if tab.get("type") == "page":
                ws_url = tab.get("webSocketDebuggerUrl")
                break
        if not ws_url:
            return jsonify({"ok": False, "error": "No Chrome page found on debug port"}), 500

        # Use websocket to send CDP command
        import websocket
        ws = websocket.create_connection(ws_url, timeout=10)
        ws.send(json.dumps({"id": 1, "method": "Page.captureScreenshot", "params": {"format": "png"}}))
        result = json.loads(ws.recv())
        ws.close()

        if "result" in result and "data" in result["result"]:
            img_data = base64.b64decode(result["result"]["data"])
            with open(filepath, "wb") as f:
                f.write(img_data)
            return jsonify({"ok": True, "file": filename})
        else:
            return jsonify({"ok": False, "error": "CDP screenshot failed"}), 500
    except Exception as e:
        return jsonify({"ok": False, "error": str(e)}), 500


# --- Pills CRUD ---

@app.route("/admin/pills")
def admin_pills():
    pills = models.get_pills()
    pills = [p for p in pills if "stretch" not in p["name"].lower()]
    for pill in pills:
        try:
            pill["schedule_times_display"] = ", ".join(json.loads(pill["schedule_times"]))
            days = json.loads(pill["schedule_days"])
            pill["schedule_days_display"] = ", ".join(d.capitalize() for d in days)
        except (json.JSONDecodeError, TypeError):
            pill["schedule_times_display"] = pill.get("schedule_times", "?")
            pill["schedule_days_display"] = "?"
    return render_template("admin/pills.html", pills=pills)


@app.route("/admin/pills/new", methods=["GET", "POST"])
def admin_pill_new():
    if request.method == "POST":
        data, error = _parse_pill_form(request)
        if error:
            flash(error, "error")
            return redirect(request.url)
        models.create_pill(data)
        return redirect("/admin/pills")
    return render_template("admin/pill_form.html", pill=None)


@app.route("/admin/pills/<int:pill_id>/edit", methods=["GET", "POST"])
def admin_pill_edit(pill_id):
    pill = models.get_pill(pill_id)
    if not pill:
        return redirect("/admin/pills")
    if request.method == "POST":
        data, error = _parse_pill_form(request)
        if error:
            flash(error, "error")
            return redirect(request.url)
        models.update_pill(pill_id, data)
        return redirect("/admin/pills")
    pill["schedule_times"] = json.loads(pill["schedule_times"])
    pill["schedule_days"] = json.loads(pill["schedule_days"])
    return render_template("admin/pill_form.html", pill=pill)


@app.route("/admin/pills/<int:pill_id>/delete", methods=["POST"])
def admin_pill_delete(pill_id):
    models.delete_pill(pill_id)
    return redirect("/admin/pills")


def _parse_pill_form(req):
    media_file = req.files.get("reminder_media_file")
    media_filename = None
    if media_file and media_file.filename:
        media_filename = secure_filename(media_file.filename)
        media_file.save(os.path.join(config.MEDIA_DIR, media_filename))

    # Accept multiple <input type="time" name="schedule_time"> fields
    times = [t.strip() for t in req.form.getlist("schedule_time") if t.strip()]
    # Also accept legacy comma-separated format
    if not times:
        times = [t.strip() for t in req.form.get("schedule_times", "").split(",") if t.strip()]
    # Validate HH:MM format
    for t in times:
        if not re.match(r"^\d{2}:\d{2}$", t):
            return None, f"Invalid time format: '{t}'. Use HH:MM (e.g. 08:00)."
    days = req.form.getlist("schedule_days") or ["mon", "tue", "wed", "thu", "fri", "sat", "sun"]

    data = {
        "name": req.form["name"],
        "dosage": req.form.get("dosage", ""),
        "instructions": req.form.get("instructions", ""),
        "schedule_times": times,
        "schedule_days": days,
        "reminder_type": req.form.get("reminder_type", "text"),
        "reminder_message": req.form.get("reminder_message", ""),
        "enabled": 1 if req.form.get("enabled") else 0,
    }
    if not times:
        return None, "At least one reminder time is required."
    if media_filename:
        data["reminder_media"] = media_filename
    return data, None


# --- Calendar CRUD ---

@app.route("/admin/calendar")
def admin_calendar():
    events = models.get_all_events()
    return render_template("admin/calendar.html", events=events)


@app.route("/admin/calendar/new", methods=["GET", "POST"])
def admin_event_new():
    if request.method == "POST":
        data = {
            "title": request.form["title"],
            "description": request.form.get("description", ""),
            "event_date": request.form["event_date"],
            "event_time": request.form.get("event_time") or None,
            "recurring": request.form.get("recurring") or None,
        }
        models.create_event(data)
        return redirect("/admin/calendar")
    return render_template("admin/event_form.html", event=None)


@app.route("/admin/calendar/<int:event_id>/edit", methods=["GET", "POST"])
def admin_event_edit(event_id):
    event = models.get_event(event_id)
    if not event:
        return redirect("/admin/calendar")
    if request.method == "POST":
        data = {
            "title": request.form["title"],
            "description": request.form.get("description", ""),
            "event_date": request.form["event_date"],
            "event_time": request.form.get("event_time") or None,
            "recurring": request.form.get("recurring") or None,
        }
        models.update_event(event_id, data)
        return redirect("/admin/calendar")
    return render_template("admin/event_form.html", event=event)


@app.route("/admin/calendar/<int:event_id>/delete", methods=["POST"])
def admin_event_delete(event_id):
    models.delete_event(event_id)
    return redirect("/admin/calendar")


# --- Jellyfin Setup ---

@app.route("/admin/plex-setup", methods=["GET", "POST"])
def admin_jellyfin_setup():
    message = None
    if request.method == "POST":
        action = request.form.get("action")

        if action == "save_url":
            models.set_setting("jellyfin_url", request.form.get("jellyfin_url", "").rstrip("/"))
            return redirect("/admin/plex-setup")

        elif action == "authenticate":
            from jellyfin_api import JellyfinAPI
            url = get_setting_or_default("jellyfin_url")
            username = request.form.get("username", "")
            password = request.form.get("password", "")
            if url and username:
                try:
                    jf = JellyfinAPI(url)
                    result = jf.authenticate(username, password)
                    models.set_setting("jellyfin_api_key", result["api_key"])
                    models.set_setting("jellyfin_user_id", result["user_id"])
                    message = f"Logged in as {result['user_name']}!"
                except Exception as e:
                    message = f"Login failed: {e}"
            return redirect("/admin/plex-setup")

    jellyfin_url = get_setting_or_default("jellyfin_url")
    api_key = get_setting_or_default("jellyfin_api_key")
    user_id = get_setting_or_default("jellyfin_user_id")

    connection = None
    libraries = []
    if jellyfin_url and api_key and user_id:
        jf = _get_jellyfin()
        if jf:
            connection = jf.test_connection()
            if connection.get("ok"):
                try:
                    libraries = jf.get_libraries()
                except Exception:
                    pass

    return render_template("admin/plex_setup.html", jellyfin_url=jellyfin_url,
                           api_key=api_key, user_id=user_id,
                           connection=connection, libraries=libraries, message=message)


# --- Family Messages Admin ---

@app.route("/admin/messages")
def admin_messages():
    messages = models.get_messages(limit=50)
    return render_template("admin/messages.html", messages=messages)


@app.route("/admin/messages/send", methods=["GET", "POST"])
def admin_message_send():
    if request.method == "POST":
        media_file = request.files.get("media_file")
        media_filename = None
        media_type = "text"

        if media_file and media_file.filename:
            media_filename = secure_filename(media_file.filename)
            media_file.save(os.path.join(config.MEDIA_DIR, media_filename))
            ext = media_filename.rsplit(".", 1)[-1].lower()
            if ext in ("jpg", "jpeg", "png", "gif", "webp"):
                media_type = "image"
            elif ext in ("mp4", "webm", "mov"):
                media_type = "video"

        msg_id = models.create_message({
            "sender": request.form.get("sender", "Family"),
            "message": request.form.get("message", ""),
            "media_type": media_type,
            "media_file": media_filename,
        })

        # Push notification to TV via SSE
        try:
            reminder_queue.put_nowait({
                "type": "family_message",
                "msg_id": msg_id,
                "sender": request.form.get("sender", "Family"),
                "message": request.form.get("message", "")[:100],
            })
        except Exception:
            pass

        return redirect("/admin/messages")
    return render_template("admin/message_form.html")


@app.route("/admin/messages/<int:msg_id>/delete", methods=["POST"])
def admin_message_delete(msg_id):
    models.delete_message(msg_id)
    # Notify TV to dismiss any active alert for this message
    try:
        reminder_queue.put_nowait({"type": "message_deleted", "msg_id": msg_id})
    except Exception:
        pass
    return redirect("/admin/messages")


# --- Birthdays ---

@app.route("/admin/birthdays")
def admin_birthdays():
    birthdays = models.get_birthdays()
    return render_template("admin/birthdays.html", birthdays=birthdays)


@app.route("/admin/birthdays/new", methods=["GET", "POST"])
def admin_birthday_new():
    if request.method == "POST":
        # Accept month/day dropdowns or legacy MM-DD text
        birth_month = request.form.get("birth_month", "")
        birth_day = request.form.get("birth_day", "")
        if birth_month and birth_day:
            birth_date = f"{birth_month}-{birth_day}"
        else:
            birth_date = request.form.get("birth_date", "")
        if not birth_date:
            flash("Please select both month and day.", "error")
            return redirect(request.url)
        data = {
            "name": request.form["name"],
            "birth_date": birth_date,
            "birth_year": int(request.form["birth_year"]) if request.form.get("birth_year") else None,
            "relationship": request.form.get("relationship", ""),
        }
        models.create_birthday(data)
        return redirect("/admin/birthdays")
    return render_template("admin/birthday_form.html", birthday=None)


@app.route("/admin/birthdays/<int:b_id>/delete", methods=["POST"])
def admin_birthday_delete(b_id):
    models.delete_birthday(b_id)
    return redirect("/admin/birthdays")


# --- Favorite Shows ---

@app.route("/admin/shows")
def admin_shows():
    shows = models.get_favorite_shows()
    return render_template("admin/shows.html", shows=shows)


@app.route("/admin/shows/new", methods=["GET", "POST"])
def admin_show_new():
    if request.method == "POST":
        data = {
            "name": request.form["name"],
            "search_term": request.form["search_term"],
            "enabled": 1 if request.form.get("enabled") else 0,
        }
        models.create_favorite_show(data)
        return redirect("/admin/shows")
    return render_template("admin/show_form.html", show=None)


@app.route("/admin/shows/<int:s_id>/delete", methods=["POST"])
def admin_show_delete(s_id):
    models.delete_favorite_show(s_id)
    return redirect("/admin/shows")


# --- Settings ---

@app.route("/admin/settings", methods=["GET", "POST"])
def admin_settings():
    if request.method == "POST":
        for key in ["greeting_names", "weather_lat", "weather_lon", "weather_unit",
                     "news_feeds", "jellyfin_url",
                     "frigate_url", "frigate_user", "frigate_pass", "frigate_cameras",
                     "ha_url", "ha_token", "ha_tv_entity",
                     "photo_interval", "photo_nas_path",
                     "immich_url", "immich_api_key", "immich_album_id",
                     "admin_password",
                     "classical_music_enabled", "classical_music_hour",
                     "tts_enabled", "audio_processing", "voice_boost", "audio_target",
                     "exercise_enabled", "exercise_hour_1", "exercise_hour_2",
                     "ip_camera_snapshot_url",
                     "stretch_enabled", "stretch_times", "stretch_duration"]:
            val = request.form.get(key)
            if val is not None:
                models.set_setting(key, val)

        # Sync stretch break pill from settings
        stretch_enabled = request.form.get("stretch_enabled", "0")
        stretch_times = request.form.get("stretch_times", "09:00,13:00,17:00,21:00")
        stretch_duration = request.form.get("stretch_duration", "15")
        times_list = [t.strip() for t in stretch_times.split(",") if t.strip()]
        with models.get_db_safe() as db:
            stretch_pill = db.execute("SELECT * FROM pills WHERE LOWER(name) LIKE '%stretch%'").fetchone()
            stretch_pill = dict(stretch_pill) if stretch_pill else None
        if stretch_enabled == "1":
            if stretch_pill:
                models.update_pill(stretch_pill["id"], {"schedule_times": times_list, "instructions": f"Time to stand up and stretch! ({stretch_duration} min)", "enabled": 1})
            else:
                models.create_pill({"name": "Stretch Break", "dosage": "", "instructions": f"Time to stand up and stretch! ({stretch_duration} min)", "schedule_times": times_list, "schedule_days": ["mon", "tue", "wed", "thu", "fri", "sat", "sun"], "enabled": 1})
        else:
            if stretch_pill:
                models.update_pill(stretch_pill["id"], {"enabled": 0})

        return redirect("/admin/settings")
    settings = {}
    for key in config.DEFAULTS:
        settings[key] = get_setting_or_default(key)
    # Also get non-default settings
    for key in ["ha_tv_entity", "immich_album_id", "admin_password",
                 "classical_music_enabled", "classical_music_hour",
                 "tts_enabled", "audio_processing", "voice_boost", "audio_target",
                 "exercise_enabled", "exercise_hour_1", "exercise_hour_2",
                 "ip_camera_snapshot_url",
                 "stretch_enabled", "stretch_times", "stretch_duration"]:
        settings[key] = models.get_setting(key) or ""

    # Immich status and albums
    immich_status = None
    immich_albums = []
    immich_photo_count = 0
    import immich_api
    if immich_api.is_configured():
        ok, msg = immich_api.test_connection()
        immich_status = {"ok": ok, "message": msg}
        immich_photo_count = immich_api.get_photo_count()
        # Fetch albums
        try:
            im_url, im_key = immich_api._get_config()
            resp = requests.get(f"{im_url}/api/albums",
                                headers={"x-api-key": im_key}, timeout=5)
            if resp.ok:
                for a in resp.json():
                    immich_albums.append({
                        "id": a["id"],
                        "name": a["albumName"],
                        "count": a.get("assetCount", 0),
                    })
        except Exception:
            pass

    return render_template("admin/settings.html", settings=settings,
                           immich_status=immich_status, immich_albums=immich_albums,
                           immich_photo_count=immich_photo_count)


# --- API for TV UI ---

@app.route("/api/home-data")
def api_home_data():
    """AJAX endpoint so the TV home screen can refresh without full reload."""
    return jsonify({
        "greeting": get_greeting(),
        "date": datetime.now().strftime("%A, %B %d"),
        "weather": get_weather_summary(),
        "next_pill": get_next_pill_info(),
        "active_reminders": list(get_active_reminders().values()),
    })


@app.route("/api/trigger-reminder/<int:pill_id>", methods=["POST"])
def api_trigger_test_reminder(pill_id):
    """Admin: trigger a test reminder for a pill."""
    from scheduler import trigger_reminder
    pill = models.get_pill(pill_id)
    if pill:
        trigger_reminder(pill, "test")
        return jsonify({"status": "triggered"})
    return jsonify({"status": "not_found"}), 404


# --- Frigate snapshot proxy ---

@app.route("/api/frigate-snapshot/<path:path>")
def frigate_snapshot_proxy(path):
    """Proxy Frigate snapshots to avoid CORS/HTTPS issues."""
    frigate_url = get_setting_or_default("frigate_url")
    if not frigate_url:
        return "", 404
    try:
        from smart_home import _frigate_cookies
        resp = requests.get(
            f"{frigate_url}/api/{path}",
            cookies=_frigate_cookies,
            verify=False,
            timeout=10,
        )
        return Response(resp.content, mimetype=resp.headers.get("content-type", "image/jpeg"))
    except Exception:
        return "", 404


# --- Photo Gallery ---

@app.route("/tv/music")
def tv_music():
    """Music player with genre browsing."""
    genre = request.args.get("genre", "")
    jf = _get_jellyfin()
    tracks = []
    if jf:
        try:
            tracks = jf.get_music_tracks(genre=genre or None, limit=30)
        except Exception:
            pass
    return render_template("tv/music.html", tracks=tracks, genre=genre)


@app.route("/tv/photos")
def tv_photos():
    """Photo frame / gallery slideshow."""
    import immich_api
    photos = _get_all_photos()
    has_immich = immich_api.is_configured()
    if not photos and not has_immich and not request.args.get("screensaver"):
        return render_template("tv/photos.html", photos=photos, has_immich=False, interval=10)
    if not photos and not has_immich and request.args.get("screensaver"):
        return redirect("/")
    interval = int(get_setting_or_default("photo_interval") or 10)
    return render_template("tv/photos.html", photos=photos, has_immich=has_immich, interval=interval)


@app.route("/admin/photos", methods=["GET", "POST"])
def admin_photos():
    if request.method == "POST":
        files = request.files.getlist("photos")
        for f in files:
            if f and f.filename:
                filename = secure_filename(f.filename)
                f.save(os.path.join(config.MEDIA_DIR, "photos", filename))
        return redirect("/admin/photos")

    photos = _get_all_photos()
    return render_template("admin/photos.html", photos=photos)


@app.route("/admin/photos/delete/<filename>", methods=["POST"])
def admin_photo_delete(filename):
    safe_name = secure_filename(filename)
    path = os.path.join(config.MEDIA_DIR, "photos", safe_name)
    if os.path.exists(path):
        os.remove(path)
    return redirect("/admin/photos")


def _get_all_photos():
    """Get all photos from the upload folder and optional NAS path."""
    photos = []
    # Uploaded photos
    photo_dir = os.path.join(config.MEDIA_DIR, "photos")
    os.makedirs(photo_dir, exist_ok=True)
    for f in sorted(os.listdir(photo_dir)):
        if f.lower().endswith(('.jpg', '.jpeg', '.png', '.gif', '.webp')):
            photos.append({"url": f"/static/media/photos/{f}", "name": f, "source": "upload"})

    # NAS photos
    nas_path = get_setting_or_default("photo_nas_path")
    if nas_path and os.path.isdir(nas_path):
        for f in sorted(os.listdir(nas_path))[:200]:  # Limit to 200
            if f.lower().endswith(('.jpg', '.jpeg', '.png', '.gif', '.webp')):
                photos.append({"url": f"/api/nas-photo/{f}", "name": f, "source": "nas"})

    # Immich photos
    import immich_api
    if immich_api.is_configured():
        photos.extend(immich_api.get_random_photos(count=30))

    return photos


@app.route("/api/has-photos")
def api_has_photos():
    import immich_api
    photos = _get_all_photos()
    has = len(photos) > 0 or immich_api.get_photo_count() > 0
    return jsonify({"has_photos": has})


@app.route("/api/nas-photo/<filename>")
def nas_photo(filename):
    """Serve a photo from the NAS path."""
    nas_path = get_setting_or_default("photo_nas_path")
    if not nas_path:
        return "", 404
    safe_name = secure_filename(filename)
    return send_from_directory(nas_path, safe_name)


@app.route("/api/jellyfin-stream/<item_id>/<path:rest>")
def jellyfin_stream_proxy(item_id, rest):
    """Proxy Jellyfin video/audio/subtitle streams for remote access."""
    if not re.match(r'^[a-f0-9]+$', item_id):
        return "", 400
    jf_url = get_setting_or_default("jellyfin_url")
    jf_key = get_setting_or_default("jellyfin_api_key")
    if not jf_url or not jf_key:
        return "", 404

    # Build the upstream URL
    upstream = f"{jf_url}/Videos/{item_id}/{rest}"
    params = dict(request.args)
    params["api_key"] = jf_key

    try:
        # Forward Range header for video seeking
        headers = {}
        if "Range" in request.headers:
            headers["Range"] = request.headers["Range"]

        # Stream the response (don't buffer entire video in memory)
        upstream_resp = requests.get(upstream, params=params, stream=True, timeout=30, headers=headers)
        if not upstream_resp.ok:
            return "", upstream_resp.status_code

        def generate():
            for chunk in upstream_resp.iter_content(chunk_size=64 * 1024):
                yield chunk

        content_type = upstream_resp.headers.get("Content-Type", "video/mp4")
        resp_headers = {}
        for h in ("Content-Length", "Accept-Ranges", "Content-Range"):
            if h in upstream_resp.headers:
                resp_headers[h] = upstream_resp.headers[h]

        return Response(generate(), status=upstream_resp.status_code,
                        mimetype=content_type, headers=resp_headers)
    except Exception:
        return "", 502


@app.route("/api/jellyfin-image/<item_id>/<image_type>")
def jellyfin_image_proxy(item_id, image_type):
    """Proxy Jellyfin images so they work from remote access."""
    if not re.match(r'^[a-f0-9]+$', item_id) or image_type not in ("Primary", "Backdrop", "Thumb", "Banner"):
        return "", 400
    jf_url = get_setting_or_default("jellyfin_url")
    jf_key = get_setting_or_default("jellyfin_api_key")
    if not jf_url or not jf_key:
        return "", 404
    width = request.args.get("w", "400")
    tag = request.args.get("tag", "")
    try:
        resp = requests.get(
            f"{jf_url}/Items/{item_id}/Images/{image_type}",
            params={"maxWidth": width, "tag": tag, "api_key": jf_key},
            timeout=10,
        )
        if resp.ok:
            r = Response(resp.content, mimetype=resp.headers.get("Content-Type", "image/jpeg"))
            r.headers["Cache-Control"] = "public, max-age=86400"
            return r
    except Exception:
        pass
    return "", 404


@app.route("/api/immich-photo/<asset_id>")
def immich_photo_proxy(asset_id):
    """Proxy an Immich photo to avoid exposing the API key to the browser."""
    if not re.match(r'^[a-f0-9-]{36}$', asset_id):
        return "", 400
    size = request.args.get("size", "preview")
    if size not in ("preview", "thumbnail"):
        size = "preview"

    import immich_api
    data, content_type = immich_api.get_photo_data(asset_id, size=size)
    if data is None:
        return "", 404
    response = app.response_class(data, mimetype=content_type)
    response.headers["Cache-Control"] = "public, max-age=86400"
    return response


@app.route("/api/next-video")
def api_next_video():
    """Get a random video to auto-play. All genres welcome — the library was curated for them.

    Tries a time-of-day preferred genre first (soft preference, not a filter).
    Validates stream URL before recommending (prevents dead streams).
    Tries up to 5 candidates to find one that works.
    """
    import random as _random
    hour = datetime.now().hour
    if hour < 14:
        preferred = ["Comedy", "Family", "Western"]
    elif hour < 17:
        preferred = ["Western", "Comedy", "Drama", "Crime"]
    else:
        preferred = ["Western", "Family", "Comedy", "Crime"]

    jf = _get_jellyfin()
    if not jf:
        return jsonify({"error": "not configured"}), 400

    def _validate_and_return(item, genre=None):
        """Check stream URL is reachable before recommending."""
        if item.get("type") == "series":
            # Series use shuffle — always valid (picks random episode server-side)
            url = f"/tv/plex/shuffle/{item['id']}"
            result = {"id": item["id"], "title": item.get("title", ""),
                      "type": item.get("type", ""), "url": url}
            if genre:
                result["genre"] = genre
            return result
        # Movie — verify stream URL exists
        try:
            stream_url = jf.get_stream_url(item["id"])
            # Stream URL is a local path — make absolute for validation
            if stream_url.startswith("/"):
                stream_url = f"http://localhost:5000{stream_url}"
            resp = requests.head(stream_url, timeout=5, allow_redirects=True)
            if resp.status_code < 400:
                url = f"/tv/plex/play/{item['id']}"
                result = {"id": item["id"], "title": item.get("title", ""),
                          "type": item.get("type", ""), "url": url}
                if genre:
                    result["genre"] = genre
                return result
        except Exception:
            pass
        return None

    try:
        libs = jf.get_libraries()
        # Try up to 5 random picks, validating each
        for attempt in range(5):
            genre = None
            if attempt < 2 and _random.random() < 0.5:
                genre = _random.choice(preferred)

            for lib in libs:
                items = jf.get_library_items(
                    lib["id"], sort="Random", genre=genre, limit=5)
                for item in items:
                    if item["id"] in _excluded_ids:
                        continue
                    result = _validate_and_return(item, genre)
                    if result:
                        return jsonify(result)
    except Exception:
        pass
    return jsonify({"error": "no content"}), 404


@app.route("/api/next-channel")
def api_next_channel():
    """Get a random time-appropriate Pluto TV channel for auto-play fallback."""
    import random as _random
    hour = datetime.now().hour
    if hour < 14:
        preferred = ["Daytime + Game Shows", "Classic TV", "News + Opinion"]
    elif hour < 17:
        preferred = ["Westerns", "Classic TV", "Comedy", "Drama"]
    else:
        preferred = ["Comedy", "Classic TV", "Westerns", "Drama"]

    try:
        import pluto_tv
        channels, _ = pluto_tv.get_channels()
        if not channels:
            return jsonify({"error": "no channels"}), 404

        # Find channels in preferred categories
        for cat in preferred:
            matching = [ch for ch in channels if ch["category"] == cat]
            if matching:
                ch = _random.choice(matching)
                return jsonify({
                    "id": ch["id"],
                    "name": ch["name"],
                    "category": ch["category"],
                    "url": f"/tv/live/play/{ch['id']}",
                })

        # Fall back to any channel
        ch = _random.choice(channels)
        return jsonify({
            "id": ch["id"],
            "name": ch["name"],
            "url": f"/tv/live/play/{ch['id']}",
        })
    except Exception:
        return jsonify({"error": "pluto unavailable"}), 500


@app.route("/api/immich-slideshow")
def api_immich_slideshow():
    """Get a batch of random Immich photos for the slideshow."""
    import immich_api
    try:
        count = min(int(request.args.get("count", 20)), 50)
    except (ValueError, TypeError):
        count = 20
    # Bypass cache to get fresh random photos
    cache.set("immich_random_20", None, ttl=0)
    photos = immich_api.get_random_photos(count=count)
    return jsonify(photos)


# --- Daily Digest API ---

@app.route("/api/daily-digest")
def api_daily_digest():
    """Get this day in history and a daily quote."""
    import random
    digest = {}

    # This Day in History (Wikipedia)
    try:
        now = datetime.now()
        resp = requests.get(
            f"https://en.wikipedia.org/api/rest_v1/feed/onthisday/selected/{now.month}/{now.day}",
            headers={"User-Agent": "SeniorTV/1.0"},
            timeout=5,
        )
        if resp.status_code == 200:
            events = resp.json().get("selected", [])
            if events:
                event = random.choice(events[:10])
                digest["history"] = {
                    "year": event.get("year", ""),
                    "text": event.get("text", ""),
                }
    except Exception:
        pass

    # Daily quote — use /api/random for rotation, /api/today for daily
    try:
        fresh = request.args.get("fresh", "0") == "1"
        quote_url = "https://zenquotes.io/api/random" if fresh else "https://zenquotes.io/api/today"
        resp = requests.get(quote_url, timeout=5)
        if resp.status_code == 200:
            quotes = resp.json()
            if quotes:
                digest["quote"] = {
                    "text": quotes[0].get("q", ""),
                    "author": quotes[0].get("a", ""),
                }
    except Exception:
        pass

    return jsonify(digest)


@app.route("/api/tv-settings")
def api_tv_settings():
    """Settings needed by the TV client (fetched once on page load)."""
    return jsonify({
        "tts_enabled": get_setting_or_default("tts_enabled") != "0",
        "audio_processing": get_setting_or_default("audio_processing") == "1",
        "voice_boost": get_setting_or_default("voice_boost") or "mild",
        "audio_target": _safe_int(get_setting_or_default("audio_target"), -14),
    })


@app.route("/api/volume-history")
def api_volume_history():
    """Room volume readings from webcam mic."""
    hours = _safe_int(request.args.get("hours"), 24)
    with models.get_db_safe() as db:
        rows = db.execute(
            """SELECT rms, db_level, sonos_volume, logged_at FROM volume_logs
               WHERE logged_at >= datetime('now', ?)
               ORDER BY logged_at""",
            (f"-{hours} hours",),
        ).fetchall()
    return jsonify([dict(r) for r in rows])


@app.route("/api/volume-stats")
def api_volume_stats():
    """Computed volume statistics: rolling averages and spike detection."""
    hours = _safe_int(request.args.get("hours"), 24)
    with models.get_db_safe() as db:
        rows = db.execute(
            """SELECT db_level, sonos_volume, logged_at FROM volume_logs
               WHERE logged_at >= datetime('now', ?)
               ORDER BY logged_at""",
            (f"-{hours} hours",),
        ).fetchall()

    if not rows:
        return jsonify({"averages": {}, "spikes": [], "summary": {}})

    data = [dict(r) for r in rows]
    dbs = [r["db_level"] for r in data]
    sonos = [r["sonos_volume"] for r in data if r["sonos_volume"] is not None]

    # Rolling averages (1min=6 samples, 5min=30, 10min=60 at 10s intervals)
    def rolling_avg(values, timestamps, window_size):
        result = []
        for i in range(len(values)):
            start = max(0, i - window_size + 1)
            window = values[start:i + 1]
            result.append({
                "logged_at": timestamps[i],
                "db_level": round(sum(window) / len(window), 1),
            })
        return result

    timestamps = [r["logged_at"] for r in data]
    avg_1m = rolling_avg(dbs, timestamps, 6)
    avg_5m = rolling_avg(dbs, timestamps, 30)
    avg_10m = rolling_avg(dbs, timestamps, 60)

    # Spike detection: readings > 2 std devs above the rolling 5min average
    import statistics
    spikes = []
    if len(dbs) > 30:
        mean = statistics.mean(dbs)
        stdev = statistics.stdev(dbs) if len(dbs) > 1 else 0
        threshold = mean + (2 * stdev)
        for i, r in enumerate(data):
            if r["db_level"] > threshold:
                spikes.append({
                    "logged_at": r["logged_at"],
                    "db_level": r["db_level"],
                    "sonos_volume": r["sonos_volume"],
                    "threshold": round(threshold, 1),
                })

    # Summary stats
    summary = {
        "count": len(dbs),
        "mean": round(statistics.mean(dbs), 1),
        "median": round(statistics.median(dbs), 1),
        "stdev": round(statistics.stdev(dbs), 1) if len(dbs) > 1 else 0,
        "min": round(min(dbs), 1),
        "max": round(max(dbs), 1),
        "spike_count": len(spikes),
        "sonos_mean": round(statistics.mean(sonos) * 100) if sonos else None,
    }

    return jsonify({
        "avg_1m": avg_1m,
        "avg_5m": avg_5m,
        "avg_10m": avg_10m,
        "spikes": spikes,
        "summary": summary,
    })


@app.route("/admin/volume")
def admin_volume():
    """Room volume trend chart."""
    return render_template("admin/volume.html")


@app.route("/api/health")
def api_health():
    """System health check for monitoring and watchdog."""
    import psutil

    health = {
        "timestamp": datetime.now().isoformat(),
        "uptime_seconds": int((datetime.now() - app_start_time).total_seconds()),
        "status": "ok",
        "checks": {},
    }

    # Disk
    disk = shutil.disk_usage("/")
    health["checks"]["disk"] = {
        "used_pct": round(disk.used / disk.total * 100, 1),
        "ok": disk.used / disk.total < 0.9,
    }

    # Memory
    mem = psutil.virtual_memory()
    health["checks"]["memory"] = {
        "used_pct": mem.percent,
        "ok": mem.percent < 85,
    }

    # Chrome process
    chrome_running = any(
        "senior-tv-chrome" in " ".join(p.info["cmdline"] or [])
        for p in psutil.process_iter(["cmdline"])
    )
    health["checks"]["chrome"] = {"running": chrome_running, "ok": chrome_running}

    # CEC
    cec_running = any(
        "cec_bridge" in " ".join(p.info["cmdline"] or [])
        for p in psutil.process_iter(["cmdline"])
    )
    cec_device = os.path.exists("/dev/cec0")
    health["checks"]["cec"] = {
        "bridge_running": cec_running,
        "device_exists": cec_device,
        "ok": True,
    }

    # Audio — check if HDMI is default sink
    try:
        audio_env = os.environ.copy()
        audio_env["XDG_RUNTIME_DIR"] = "/run/user/1000"
        result = subprocess.run(
            ["wpctl", "status"], capture_output=True, text=True, timeout=5,
            env=audio_env
        )
        hdmi_default = False
        for line in result.stdout.split("\n"):
            if "*" in line and ("hdmi" in line.lower() or "rembrandt" in line.lower()):
                hdmi_default = True
                break
        health["checks"]["audio"] = {"hdmi_default": hdmi_default, "ok": hdmi_default}
    except Exception:
        health["checks"]["audio"] = {"hdmi_default": False, "ok": False}

    # Jellyfin
    try:
        jf_url = get_setting_or_default("jellyfin_url")
        resp = requests.get(f"{jf_url}/System/Ping", timeout=3)
        health["checks"]["jellyfin"] = {"reachable": resp.ok, "ok": resp.ok}
    except Exception:
        health["checks"]["jellyfin"] = {"reachable": False, "ok": False}

    # Internet
    try:
        requests.get("https://api.open-meteo.com/v1/forecast?latitude=0&longitude=0&current=temperature_2m", timeout=5)
        health["checks"]["internet"] = {"reachable": True, "ok": True}
    except Exception:
        health["checks"]["internet"] = {"reachable": False, "ok": False}

    # Tailscale
    try:
        ts = subprocess.run(["tailscale", "status", "--json"], capture_output=True, text=True, timeout=5)
        ts_state = json.loads(ts.stdout).get("BackendState", "")
        health["checks"]["tailscale"] = {"state": ts_state, "ok": ts_state == "Running"}
    except Exception:
        health["checks"]["tailscale"] = {"state": "unknown", "ok": False}

    # Watchdog repair count
    try:
        with open("/tmp/senior_tv_repair_count") as f:
            repair_count = int(f.read().strip())
    except Exception:
        repair_count = 0
    health["checks"]["watchdog"] = {"repairs_today": repair_count, "ok": repair_count < 20}

    # Scheduler
    from scheduler import scheduler as _sched
    health["checks"]["scheduler"] = {"running": _sched.running, "ok": _sched.running}

    # Immich
    try:
        import immich_api
        if immich_api.is_configured():
            ok, msg = immich_api.test_connection()
            health["checks"]["immich"] = {"connected": ok, "detail": msg, "ok": ok}
    except Exception:
        pass

    # Inactivity
    try:
        last_activity = models.get_last_activity_time()
        threshold_hours = int(get_setting_or_default("inactivity_alert_hours") or "4")
        now = datetime.now()
        is_daytime = 8 <= now.hour < 22
        if last_activity:
            last_dt = datetime.fromisoformat(last_activity)
            hours_idle = round((now - last_dt).total_seconds() / 3600, 1)
            inactivity_ok = hours_idle < threshold_hours if is_daytime else True
            health["checks"]["inactivity"] = {"ok": inactivity_ok, "hours_idle": hours_idle, "last_activity": last_activity, "threshold_hours": threshold_hours}
        else:
            health["checks"]["inactivity"] = {"ok": not is_daytime, "hours_idle": None, "last_activity": None, "threshold_hours": threshold_hours}
    except Exception:
        health["checks"]["inactivity"] = {"ok": True, "hours_idle": None, "last_activity": None, "threshold_hours": 4}

    # Overall
    all_ok = all(c.get("ok", True) for c in health["checks"].values())
    health["status"] = "ok" if all_ok else "degraded"
    return jsonify(health)


# ========================================
# Startup
# ========================================

_smart_home_monitor = None

def _start_smart_home():
    """Start the Frigate doorbell monitor if configured."""
    global _smart_home_monitor
    frigate_url = get_setting_or_default("frigate_url")
    frigate_user = get_setting_or_default("frigate_user")
    frigate_pass = get_setting_or_default("frigate_pass")

    if frigate_url and frigate_user and frigate_pass:
        from smart_home import SmartHomeMonitor
        ha_url = get_setting_or_default("ha_url")
        ha_token = get_setting_or_default("ha_token")
        cameras_str = get_setting_or_default("frigate_cameras") or "front_door"
        cameras = [c.strip() for c in cameras_str.split(",")]

        _smart_home_monitor = SmartHomeMonitor(
            frigate_url, frigate_user, frigate_pass,
            ha_url, ha_token, reminder_queue, cameras,
        )
        _smart_home_monitor.start()
        print(f"Smart home monitor started (cameras: {cameras})")


if __name__ == "__main__":
    import warnings
    warnings.filterwarnings("ignore", message="Unverified HTTPS request")

    models.init_db()
    for key, val in config.DEFAULTS.items():
        if models.get_setting(key) is None:
            models.set_setting(key, val)
    start_scheduler()
    _start_smart_home()
    # Start TV room presence monitor
    from smart_home import start_presence_monitor
    start_presence_monitor(alert_queue=reminder_queue)
    print("Presence monitor started (tv_room webcam)")
    try:
        debug_mode = os.environ.get("SENIOR_TV_DEBUG", "0") == "1"
        app.run(host="0.0.0.0", port=5000, debug=debug_mode, threaded=True)
    finally:
        stop_scheduler()
        if _smart_home_monitor:
            _smart_home_monitor.stop()
